#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math

DATA_SIZE = 1375
WINDOW_SIZE = 2

class Sender:
    def __init__(self, host, port):
        self.host = host
        self.remote_port = int(port)
        self.log("Sender starting up using port %s" % self.remote_port)
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))
        self.waiting = False

        self.send_sequence_number = 0
        self.recv_sequence_number = 0
        self.window = {}
        self.listNum = []

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def send(self, message):
        self.send_sequence_number += 1
        message['snum'] = self.send_sequence_number
        message['rnum'] = self.recv_sequence_number
        self.socket.sendto(json.dumps(message).encode('utf-8'), (self.host, self.remote_port))
        self.window[self.send_sequence_number] = message

    def run(self):
        while True:
            sockets = [self.socket, sys.stdin] if not self.waiting else [self.socket]

            socks = select.select(sockets, [], [], 0.1)[0]
            for conn in socks:
                if conn == self.socket:
                    k, addr = conn.recvfrom(65535)
                    msg = k.decode('utf-8')

                    self.log("Received message '%s'" % msg)
                    msg = json.loads(msg)
                    self.recv_sequence_number = msg['rnum']
                    self.waiting = False
                elif conn == sys.stdin:
                    data = sys.stdin.read(DATA_SIZE)
                    if len(data) == 0:
                        self.log("All done!")
                        sys.exit(0)

                    msg = { "type": "msg", "data": data }
                    self.log("Sending message '%s'" % msg)
                    self.send(msg)
                    self.waiting = True

        return

    def run2(self):
        
        while True:
            while len(self.window) != 0:
                socks = select.select([self.socket], [], [], 0.1)[0]
                for conn in socks:
                    if conn == self.socket:
                        k, addr = conn.recvfrom(65535)
                        msg = k.decode('utf-8')
                        msg = json.loads(msg)
                        if msg['rnum'] not in self.listNum:
                            self.listNum.append(msg['rnum'])
                            self.recv_sequence_number = msg['rnum']
                            self.log("Received ack for message '%s'" % msg)
                            self.log('Deleting %s from %s' % (msg['snum'],self.window))
                            del self.window[msg['snum']]
                        else:
                            self.log('Dup rnum %s' % (msg['rnum']))
            
            while len(self.window) < WINDOW_SIZE:
                data = sys.stdin.read(DATA_SIZE)
                msg = {"type": "msg", "data": data}
                if len(data) == 0:
                    if len(self.window) != 0:
                        break
                    else:
                        self.log("All done!")
                        sys.exit(0)
                self.log("Sending message '%s'" % msg)
                self.send(msg)
        
        self.log("All done!")
        sys.exit(0)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('host', type=str, help="Remote host to connect to")
    parser.add_argument('port', type=int, help="UDP port number to connect to")
    args = parser.parse_args()
    sender = Sender(args.host, args.port)
    sender.run2()
